# generate_cosmology_snapshots.py

import numpy as np
from void_analysis.cosmology_inference import (
    Ez2,
    Hz,
    f_lcdm,
    ap_parameter
)

# List of snapshots generated by this script
GENERATED_SNAPSHOTS = [
    "Ez2_ref.npy",
    "Hz_ref.npy",
    "f_lcdm_ref.npy",
    "ap_parameter_ref.npy"
]

def generate_snapshots():
    z_long = np.linspace(0, 2, 100)
    z_short = np.linspace(0, 2, 50)
    Om = 0.31
    Om_fid = 0.3

    # Generate snapshots
    Ez2_vals = Ez2(z_long, Om)
    Hz_vals = Hz(z_long, Om)
    f_vals = f_lcdm(z_long, Om)
    ap_vals = ap_parameter(z_short, Om, Om_fid)

    np.save("Ez2_ref.npy", Ez2_vals)
    np.save("Hz_ref.npy", Hz_vals)
    np.save("f_lcdm_ref.npy", f_vals)
    np.save("ap_parameter_ref.npy", ap_vals)

    print("✅ Cosmology utility snapshots saved!")

if __name__ == "__main__":
    generate_snapshots()

