import numpy as np
import scipy

from void_analysis.cosmology_inference import (
    get_D_coefficients,
    get_ic_polynomial_coefficients,
    get_nonperturbative_polynomial_coefficients,
    get_taylor_polynomial_coefficients,
    get_initial_condition_non_perturbative,
    get_initial_condition,
    get_S1r,
    get_S2r,
    get_S3r,
    get_S4r,
    get_S5r,
    get_psi_n_r,
    get_delta_lpt,
    get_eulerian_ratio_from_lagrangian_ratio,
    process_radius,
    spherical_lpt_displacement,
    spherical_lpt_velocity,
    void_los_velocity_ratio_1lpt
)

from void_analysis.simulation_tools import gaussian_delta, gaussian_Delta

# List of snapshots generated by this script
GENERATED_SNAPSHOTS = [
    "D_coefficients.npy",
    "A_poly_coefficients.npy",
    "B_poly_coefficients.npy",
    "Bp_poly_coefficients.npy",
    "NonPert_initial_conditions.npy",
    "Pert_initial_conditions.npy",
    "S1r_data.npy",
    "S2r_data.npy",
    "S3r_data.npy",
    "S4r_data.npy",
    "S5r_data.npy",
    "psi_n_r.npy",
    "Delta_lpt.npy",
    "eulerian_ratio_data.npz",
    "lpt_displacement.npy",
    "lpt_velocity.npy",
    "test_void_los_velocity_ratio_1lpt.npy"
]



def generate_snapshots():
    # Test data:
    Om = 0.3
    rvals = np.linspace(0,3,101)
    A = 0.85
    sigma = 1
    delta_f = lambda r: gaussian_delta(r,A=A,sigma=sigma)
    Delta_f = lambda r: gaussian_Delta(r,A=A,sigma=sigma)
    Delta = delta_f(rvals)
    Psi_n = [0.5**n*np.exp(-rvals**2/(2*n**2)) for n in range(1,6)]

    # Generate snapshots
    D_coeffs = get_D_coefficients(Om,order=5,return_all=True)
    A_coeffs = get_ic_polynomial_coefficients(5,Om=0.3)
    B_coeffs = get_nonperturbative_polynomial_coefficients(5,Om=0.3)
    Bp_coeffs = get_taylor_polynomial_coefficients(5,Om=0.3)
    nonpert_ics = get_initial_condition_non_perturbative(
        Delta,order=5,Om=0.3,use_linear_on_fail=False,
        taylor_expand = False,
    )
    pert_ics = get_initial_condition(
        Delta,order=4,Om=0.3,use_linear_on_fail=False
    )
    S1r = get_S1r(
        Delta,rvals,0.3,order=5,perturbative_ics = False,
        taylor_expand=False,force_linear_ics = False
    )
    S2r = get_S2r(
        Delta,rvals,0.3,order=5,perturbative_ics = False,
        taylor_expand=False,force_linear_ics = False
    )
    S3r = get_S3r(
        Delta,rvals,0.3,order=5,perturbative_ics = False,
        taylor_expand=False,force_linear_ics = False
    )
    S4r = get_S4r(
        Delta,rvals,0.3,order=5,perturbative_ics = False,
        taylor_expand=False,force_linear_ics = False
    )
    S5r = get_S5r(
        Delta,rvals,0.3,order=5,perturbative_ics = False,
        taylor_expand=False,force_linear_ics = False
    )
    psi_n_r = get_psi_n_r(
        Delta,rvals,5,z=0,Om=0.3,order=5,return_all=True
    )
    Delta_lpt = get_delta_lpt(
        Delta,z=0,Om=0.3,order=5,return_all=True
    )
    fully_expanded = get_eulerian_ratio_from_lagrangian_ratio(
        Psi_n,Psi_n,5,expand_denom_only=False
    )
    denom_only = get_eulerian_ratio_from_lagrangian_ratio(
        np.sum(Psi_n,0),Psi_n,5,expand_denom_only=True
    )
    psi_lpt = spherical_lpt_displacement(
        rvals,Delta,order=5,z=0,Om=0.3,
        fixed_delta = True,
        radial_fraction = True,eulerian_radius=False,
        expand_denom_only=False,taylor_expand=False,
        expand_euler_ratio=False
    )
    v_lpt = spherical_lpt_velocity(
        rvals,Delta,order=5,z=0,Om=0.3,radial_fraction = True,
        fixed_delta = True,eulerian_radius=False,
        taylor_expand=False,expand_denom_only=False,
        expand_euler_ratio=False,return_all=False
    )
    
    vlpt_ratio = void_los_velocity_ratio_1lpt(rvals,Delta_f,0.53)
    vlpt_deriv = void_los_velocity_ratio_derivative_1lpt(
        rvals,Delta_f,delta_f,0.53
    )

    np.save("D_coefficients.npy", D_coeffs)
    np.save("A_poly_coefficients.npy",A_coeffs)
    np.save("B_poly_coefficients.npy",B_coeffs)
    np.save("Bp_poly_coefficients.npy",Bp_coeffs)
    np.save("NonPert_initial_conditions.npy",nonpert_ics)
    np.save("Pert_initial_conditions.npy",pert_ics)
    np.save("S1r_data.npy",S1r)
    np.save("S2r_data.npy",S2r)
    np.save("S3r_data.npy",S3r)
    np.save("S4r_data.npy",S4r)
    np.save("S5r_data.npy",S5r)
    np.save("psi_n_r.npy",psi_n_r)
    np.save("Delta_lpt.npy",Delta_lpt)
    np.savez(
        "eulerian_ratio_data.npz",fully_expanded=fully_expanded,
        denom_only=denom_only
    )
    np.save("lpt_displacement.npy",psi_lpt)
    np.save("lpt_velocity.npy",v_lpt)
    np.save("test_void_los_velocity_ratio_1lpt.npy",vlpt_ratio)
    np.save("test_void_los_velocity_ratio_derivative_1lpt.npy",vlpt_deriv)

    print("✅ LPT snapshots saved!")

if __name__ == "__main__":
    generate_snapshots()
